language: node_js

node_js:
- '6'
- 6.2.2
- '7'

matrix:
  allow_failures:
    - node_js: '7'

cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
before_install:
- npm install -g npm@latest yarn@latest
install:
- yarn
script:
- yarn test
